### ISSUE TITLE
change library from mohammad

### ISSUE THREAD

**Issue by honeyamin** [bkhezry/PersianDateRangePicker#2]
tnx for your fantastic code.
can u help me to resolve this please?
i use library that mohamad created(com.mohamadamin:persianmaterialdatetimepicker:1.2.1)
now i want to change my code and use your library but i dont know that how can edite my "onDateSet".
this is my code:

`@Override
    public void onDateSet(DatePickerDialog view, int year, int monthOfYear, int dayOfMonth) {
        String symbol = "-";
        String date = Utility.getPersianData(year, monthOfYear, dayOfMonth , symbol);

        monthOfYear++;

        if (request == SELECT_FROM)
        {
            dateFrom = Utility.getGlobalData(year, monthOfYear, dayOfMonth, symbol);
            btnFrom.setText(date);
        }
        else if (request == SELECT_TO)
        {
            dateTo = Utility.getGlobalData(year, monthOfYear, dayOfMonth, symbol);
            btnTO.setText(date);
        }
        if (dateFrom!=null && dateTo!=null)
        {
            if (Utility.hasPermission(dateFrom,dateTo,symbol))
                dateIsSelected = true;
            else {
                dateIsSelected = false;
                Toast.makeText(getApplicationContext(), "بازه انتخابی اشتباه است", Toast.LENGTH_LONG).show();
            }
        }
    }`

**Comment by bkhezry** [comment]
Hi,
You're welcome :-)
please see the sample code in this line:
https://github.com/bkhezry/PersianDateRangePicker/blob/master/sample/src/main/java/com/bkhezry/persiandaterangepickerexample/MainActivity.java#L94

```java
@Override
  public void onDateSet(PersianDatePickerDialog view, int year, int monthOfYear, int dayOfMonth, int yearEnd, int monthOfYearEnd, int dayOfMonthEnd) {
    String monthString = String.valueOf(monthOfYear + 1);
    if (monthOfYear < 9) {
      monthString = "0" + monthString;
    }
    String dayString = String.valueOf(dayOfMonth);
    if (dayOfMonth < 10) {
      dayString = "0" + dayString;
    }
    String monthStringEnd = String.valueOf(monthOfYearEnd + 1);
    if (monthOfYearEnd < 9) {
      monthStringEnd = "0" + monthStringEnd;
    }
    String dayStringEnd = String.valueOf(dayOfMonthEnd);
    if (dayOfMonthEnd < 10) {
      dayStringEnd = "0" + dayStringEnd;
    }
    fromDate.setText(String.format("%s/%s/%s", LanguageUtils.getPersianNumbers(String.valueOf(year)), LanguageUtils.getPersianNumbers(monthString), LanguageUtils.getPersianNumbers(dayString)));
    toDate.setText(String.format("%s/%s/%s", LanguageUtils.getPersianNumbers(String.valueOf(yearEnd)), LanguageUtils.getPersianNumbers(monthStringEnd), LanguageUtils.getPersianNumbers(dayStringEnd)));
  }
```
