### ISSUE TITLE
خیلی گلی

### ISSUE THREAD

**Issue by ghost** [bkhezry/PersianDateRangePicker#3]
دمت گرم داداش عالیهههههه

**Comment by bkhezry** [comment]
:-)

**Comment by ghost** [comment]
اقا سلام ... خوبین
ببخشید می خواستم بگم تقویم روی اندروید 8 کار نمی کنه ..... نو رو خدا اگه
میشه درستش کنید ... ما پروژه مون رو هواس

**Comment by bkhezry** [comment]
@NooriArdestani سلام
من همین الان دمو کتابخانه رو با اندروید هشت و در نکسوس ۵ایکس تست کردم. هم تاریخ و هم ساعت رو تونستم باهاش انتخاب کنم. عکسش رو هم ضمیمه می‌کنم. اگر مشکل رو بتونی شرح بدی شاید بتونم کمکی بکنم.
![selection_020](https://user-images.githubusercontent.com/91809/47965396-ff058e00-e05b-11e8-8221-aebc8df2a0b1.png)
